Controllers/AgentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SupportService.Interfaces;

namespace SupportService.Controllers
{
    public class AgentController : Controller
    {
        private readonly ILogger logger;
        private readonly IAgentRepository agentRepository;

        public AgentController(IAgentRepository agentRepository, ILoggerFactory loggerFactory)
        {
            this.agentRepository = agentRepository;
            this.logger = loggerFactory.CreateLogger(nameof(AgentController));
        }
        // GET: Agent
        public IActionResult Index()
        {
            var agents = agentRepository.GetAllAgents();
            return View(agents);
        }

        // GET: Agent/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: Agent/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Agent/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Agent/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Agent/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Agent/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Agent/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SupportService.Entities;
using SupportService.Interfaces;

namespace SupportService.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductRepository productRepository;
        private readonly ILogger logger;
        private readonly AppDbContext _context;
        public ProductController(IProductRepository productRepository, ILoggerFactory logger, AppDbContext context)
        {
            this._context = context;
            this.logger = logger.CreateLogger(nameof(ProductController));
            this.productRepository = productRepository;
        }
        // GET: Product
        public IActionResult Index()
        {
            var product = productRepository.GetProducts();
            return View(product);
        }

        // GET: Product/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            //if (ModelState.IsValid)
            //{
            //    _ = productRepository.Add(product);
            //    //_context.SaveChangesAsync(product);
            //    return RedirectToAction(nameof(Index));
            //}
            return View();
        }

        // POST: Product/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _ = productRepository.Add(product);
                    //_context.SaveChangesAsync(product);
                    return RedirectToAction(nameof(Index));
                }

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Product/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Product/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Product/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/TicketController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SupportService.Entities;
using SupportService.Interfaces;
using SupportService.Model;

namespace SupportService.Controllers
{
    //[Authorize]
    public class TicketController : Controller
    {
        private readonly AppDbContext context;
        private readonly ITicketRepository ticketRepository;
        private readonly ICustomerRepository customerRepository;
        private readonly ILogger logger;
        private readonly IProductRepository productRepository;
        private UserManager<AppUser> _userManager;

        public TicketController(ITicketRepository ticketRepository,
            ICustomerRepository customerRepository,
            ILoggerFactory loggerFactory,
            IProductRepository productRepository,
            AppDbContext context,
            UserManager<AppUser> userManager)
        {
            this.context = context;
            this.ticketRepository = ticketRepository;
            this.customerRepository = customerRepository;
            this.productRepository = productRepository;
            _userManager = userManager;
            logger = loggerFactory.CreateLogger(nameof(TicketController));
        }

        [HttpGet]
        //[ProducesResponseType(typeof(List<Ticket>), 200)]
        //[ProducesResponseType(typeof(ApiResponse), 400)]
        public async Task<IActionResult> Index()
        {
            try
            {
                var product = productRepository.GetProducts();
                var tickets = await ticketRepository.GetTickets();
                return View(tickets);
            }
            catch (System.Exception e)
            {
                logger.LogError($"Error in {nameof(TicketController)} " + e.Message);
                return BadRequest(new ApiResponse { Status = false });
            }

        }
        [HttpGet]
        
        public IActionResult Create()
        {
            ViewBag.Product = context.Products;
            return View();
        }
        [HttpPost, ValidateAntiForgeryToken]
        public  IActionResult Create(Ticket ticket)
        {
            try
            {
                var username = User.Identity.Name;
                if (ModelState.IsValid)
                {
                    //ticket.IssuingCustomer = username;
                    ticketRepository.Add(ticket);
                    return RedirectToAction(nameof(Index));
                }
                return RedirectToAction(nameof(Index));

            }
            catch (System.Exception e)
            {
                logger.LogError($"Error in { nameof(TicketController)} " + e.Message);
                return View();
            }

        }

    }
}

ViewComponent/LoginLogoutViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SupportService.ViewComponents
{
    public class LoginLogoutViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke() => View();
        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TH Support</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Support Service</a>
            </div>

            
            <ul class="nav navbar-nav">
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.IsInRole("Admin"))
                    {
                        <li><a asp-area="" asp-controller="Product" asp-action="Index">Product</a></li>
                        <li><a asp-area="" asp-controller="Ticket" asp-action="Index">Ticket</a></li>
                        <li><a asp-area="" asp-controller="Agent" asp-action="Index">Agent</a></li>
                        @*<li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">Reports <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a asp-area="" asp-controller="Charts" asp-action="Bar">Employee vs Task</a></li>
                                <li><a asp-area="" asp-action="Pie" asp-controller="Charts">Task vs Duration</a></li>
                            </ul>
                        </li>*@
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>

                    }



                }

            </ul>
            
            
                <div>
                    @await Component.InvokeAsync("LoginLogout")
                </div>
                    
            
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer >
            <p>&copy; 2020 - Tech Heights Limited</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TH Support</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SupportService</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - TH Support Service - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>